# Generated by Django 3.2.23 on 2024-02-20 11:49

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='app',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Users'), ('circles', 'Circles'), ('groups', 'Groups'), ('registration', 'Registration'), ('settings', 'Settings')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=256, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
